version: '3.9'
services:
  app:
    build: .
    depends_on:
      - mongodb
    volumes:
      - .:/app
  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
